import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar/Navbar";
import Footer from "./_components/Footer/Footer";
import { Toaster } from "react-hot-toast";

import Providers from "./providers/react-query-provider";
import NextauthProviider from "./providers/nextauthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 return (
  <html lang="en">

    <body 
      className={`${geistSans.variable} ${geistMono.variable} antialiased`} 
      suppressHydrationWarning
    >
      <Providers>

    <NextauthProviider>
    <Navbar/>
      <div className="container mx-auto  min-h-screen  mt-12 px-3">
        <Toaster/>
       
        {children} 
      </div>
   <Footer/>
    </NextauthProviider>
      </Providers>

     
  
    </body>
  </html>
);
}
